### ISSUE TITLE
Bootloop after QPR2 merged

### ISSUE THREAD

**Issue by AmeChanRain** [Diva-Room/Miku_device_xiaomi_violet#1]
```
03-16 19:11:17.120  3041  3041 D AndroidRuntime: Shutting down VM
03-16 19:11:17.120  3041  3041 E AndroidRuntime: FATAL EXCEPTION: main
03-16 19:11:17.120  3041  3041 E AndroidRuntime: Process: com.android.systemui, PID: 3041
03-16 19:11:17.120  3041  3041 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.android.systemui.SystemUIService: java.lang.IllegalArgumentException: Component class com.android.systemui.notetask.shortcut.CreateNoteTaskShortcutActivity does not exist in com.android.systemui
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4495)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2157)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Component class com.android.systemui.notetask.shortcut.CreateNoteTaskShortcutActivity does not exist in com.android.systemui
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2920)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:5881)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:3052)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.systemui.wmshell.WMShell.start(WMShell.java:157)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.startStartable(SystemUIApplication.java:36)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication$$ExternalSyntheticLambda3.run(R8$$SyntheticClass:58)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.timeInitialization(SystemUIApplication.java:27)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:20)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:6)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:9)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4482)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	... 9 more
03-16 19:11:17.120  3041  3041 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.setEnabledSettings(PackageManagerService.java:3791)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.-$$Nest$msetEnabledSettings(Unknown Source:0)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.setComponentEnabledSetting(PackageManagerService.java:5598)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2931)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:5975)
03-16 19:11:17.120  3041  3041 E AndroidRuntime: 
```

Still investigating.

**Comment by AmeChanRain** [comment]
Done.
Ref: https://github.com/Diva-Room/Miku_device_xiaomi_violet/commit/262b73f4a30be8e58ac3136c2d26aff0d53e6907
